const firebaseConfig={apiKey:"AIzaSyBI_6e7KQs4NBJ9ZaLe1FaPxV3xcYE8t3g",authDomain:"donflix-a85da.firebaseapp.com",databaseURL:"https://donflix-a85da-default-rtdb.firebaseio.com",projectId:"donflix-a85da",storageBucket:"donflix-a85da.firebasestorage.app",messagingSenderId:"236646922585",appId:"1:236646922585:web:d5a6778879dfb58eb03448"};firebase.initializeApp(firebaseConfig);let currentVideoId=null;const urlParams=new URLSearchParams(window.location.search);const serieId=urlParams.get('id');const db=firebase.database();const serieRef=db.ref(`series/${serieId}`);serieRef.once('value',function(snapshot){const serie=snapshot.val();if(!serie)return;document.querySelector('.banner-container').innerHTML=`
    <img src="${serie.banner}" alt="${serie.nombre}">
`;document.querySelector('.serie-titulo').textContent=serie.nombre;const temporadasContainer=document.querySelector('.temporadas-container');temporadasContainer.innerHTML='';Object.entries(serie.temporadas||{}).forEach(([temporadaKey,temporada])=>{const temporadaElement=document.createElement('div');temporadaElement.classList.add('temporada');const capitulos=Object.entries(temporada).map(([key,videoId])=>({numero:parseInt(key.match(/\d+/)[0]),videoId:videoId})).sort((a,b)=>a.numero-b.numero);temporadaElement.innerHTML=`
        <h2 class="temporada-titulo">Temporada ${temporadaKey.replace('temporada', '')}</h2>
        <div class="episodios-grid">
            ${capitulos.map((capitulo, index) => `<div class="episodio" onclick="playVideo('${capitulo.videoId}')"><h3>Capítulo ${index+1}</h3></div>`).join('')}
        </div>
    `;temporadasContainer.appendChild(temporadaElement)})});function verificarVIP(){auth.onAuthStateChanged((user)=>{if(user){const userId=user.uid;const userRef=firebase.database().ref(`usuarios/${userId}/nivel_de_plan`);userRef.on('value',(snapshot)=>{const nivelDePlan=snapshot.val();if(nivelDePlan&&(nivelDePlan==='vip1'||nivelDePlan==='vip2'||nivelDePlan==='vip3'||nivelDePlan==='vip4')){document.querySelectorAll('.episodio').forEach((episodio)=>{episodio.style.pointerEvents='auto'})}else{mostrarNotificacion();document.querySelectorAll('.episodio').forEach((episodio)=>{episodio.style.pointerEvents='none'})}})}else{mostrarNotificacion()}})}
function mostrarNotificacion(){Swal.fire({icon:'error',title:'¡Acceso denegado!',text:'No tienes acceso VIP para ver esta serie.',confirmButtonText:'Cerrar',background:'#f8d7da',color:'#721c24',confirmButtonColor:'#721c24',})}
function playVideo(videoId){currentVideoId=videoId;document.querySelector('.overlay').style.display='block';document.querySelector('.mensaje-modal').style.display='block'}
function confirmarReproduccion(){document.querySelector('.mensaje-modal').style.display='none';document.querySelector('.video-player').style.display='block';const videoPlayer=document.querySelector('.video-player');const iframe=videoPlayer.querySelector('iframe');const videoUrl=`https://drive.google.com/file/d/${currentVideoId}/preview`;iframe.src=videoUrl;videoPlayer.classList.add('active')}
document.querySelector('.close-video').addEventListener('click',function(){const videoPlayer=document.querySelector('.video-player');const iframe=videoPlayer.querySelector('iframe');iframe.src='';videoPlayer.style.display='none';document.querySelector('.overlay').style.display='none';currentVideoId=null});verificarVIP()