if(!firebase.apps.length){firebase.initializeApp(firebaseConfig)}
const database=firebase.database();let currentSlide=0;let slides=[];function createCarouselItems(data){const imageContainer=document.getElementById('x-carousel-container');const contentContainer=document.getElementById('x-carousel-content');const dotsContainer=document.getElementById('x-carousel-dots');imageContainer.innerHTML='';contentContainer.innerHTML='';dotsContainer.innerHTML='';slides=Object.values(data);slides.forEach((slide,index)=>{const imageItem=document.createElement('div');imageItem.className=`x-carousel-item ${index === 0 ? 'active' : ''}`;const backgroundImage=document.createElement('div');backgroundImage.className='x-background-image';backgroundImage.style.backgroundImage=`url(${slide.backgroundImage})`;imageItem.appendChild(backgroundImage);imageContainer.appendChild(imageItem);const content=document.createElement('div');content.className=`x-content ${index === 0 ? 'active' : ''}`;content.style.display=index===0?'block':'none';content.innerHTML=`
            <h1 class="x-title">${slide.title}</h1>
            <p class="x-subtitle">${slide.subtitle}</p>
            <p class="x-description">${slide.description}</p>
           
            <a href="detalles.html?id=${slide.id}" class="x-watch-button">Ver en donflix</a>
        `;contentContainer.appendChild(content);const dot=document.createElement('div');dot.className=`x-carousel-dot ${index === 0 ? 'active' : ''}`;dot.addEventListener('click',()=>goToSlide(index));dotsContainer.appendChild(dot)})}
document.addEventListener('DOMContentLoaded',()=>{if(window.innerWidth<=768){const mobileCarouselContainer=document.createElement('div');mobileCarouselContainer.id='x-mobile-carousel';mobileCarouselContainer.className='x-mobile-carousel';const prevArrow=document.createElement('button');prevArrow.className='x-mobile-carousel-arrow x-mobile-carousel-prev';prevArrow.innerHTML='‹';const nextArrow=document.createElement('button');nextArrow.className='x-mobile-carousel-arrow x-mobile-carousel-next';nextArrow.innerHTML='›';document.body.insertBefore(mobileCarouselContainer,document.querySelector('.x-carousel'));database.ref('mobile-carousel').once('value').then((snapshot)=>{const mobileSlides=snapshot.val();if(mobileSlides){let currentMobileSlide=0;const slides=Object.values(mobileSlides);function renderMobileCarousel(){mobileCarouselContainer.innerHTML='';const currentSlide=slides[currentMobileSlide];const slideElement=document.createElement('div');slideElement.className='x-mobile-slide';slideElement.innerHTML=`
                            <div class="x-mobile-slide-background" style="background-image: url(${currentSlide.backgroundImage})"></div>
                            <div class="x-mobile-slide-content">
                                <h2>${currentSlide.title}</h2>
                                <p>${currentSlide.description}</p>
                                <div class="x-mobile-slide-actions">
                               
                                    <a href="detalles.html?id=${currentSlide.id}" class="x-mobile-info-btn">Ver en donflix</a>
                                </div>
                            </div>
                        `;mobileCarouselContainer.appendChild(slideElement);mobileCarouselContainer.appendChild(prevArrow);mobileCarouselContainer.appendChild(nextArrow);prevArrow.onclick=()=>{currentMobileSlide=(currentMobileSlide-1+slides.length)%slides.length;renderMobileCarousel()};nextArrow.onclick=()=>{currentMobileSlide=(currentMobileSlide+1)%slides.length;renderMobileCarousel()}}
renderMobileCarousel()}}).catch((error)=>{console.error('Error loading mobile carousel:',error)})}});function goToSlide(index){const imageItems=document.querySelectorAll('.x-carousel-item');const contentItems=document.querySelectorAll('.x-content');const dots=document.querySelectorAll('.x-carousel-dot');imageItems[currentSlide].classList.remove('active');contentItems[currentSlide].style.display='none';dots[currentSlide].classList.remove('active');currentSlide=index;imageItems[currentSlide].classList.add('active');contentItems[currentSlide].style.display='block';dots[currentSlide].classList.add('active')}
document.querySelector('.x-carousel-next').addEventListener('click',()=>{const nextSlide=(currentSlide+1)%slides.length;goToSlide(nextSlide)});document.querySelector('.x-carousel-prev').addEventListener('click',()=>{const prevSlide=(currentSlide-1+slides.length)%slides.length;goToSlide(prevSlide)});database.ref('carousel').once('value').then((snapshot)=>{const data=snapshot.val();if(data){createCarouselItems(data)}}).catch((error)=>{console.error('Error loading carousel data:',error)});database.ref('carousel').on('value',(snapshot)=>{const data=snapshot.val();if(data){createCarouselItems(data)}})